CREATE TABLE "WF_OPINION_HISTORY"
(
"ID" NUMBER NOT NULL,
"OPINION_ID" NUMBER,
"APPROVER_NAME" VARCHAR2(50),
"APPROVE_TIME" VARCHAR2(100),
"APPROVE_OPINION" VARCHAR2(3000),
"OPERATOR_ID" NUMBER,
"OPERATOR_NAME" VARCHAR2(50),
"OPERATOR_TIME" DATETIME(6),
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "WF_OPINION_HISTORY" IS '意见修改历史表';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."OPINION_ID" IS '意见表的id';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."APPROVER_NAME" IS '意见表审批人修改';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."APPROVE_TIME" IS '意见表审批时间修改';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."APPROVE_OPINION" IS '意见表意见修改';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."OPERATOR_ID" IS '操作人id';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."OPERATOR_NAME" IS '操作人';
COMMENT ON COLUMN "WF_OPINION_HISTORY"."OPERATOR_TIME" IS '操作时间';