
CREATE TABLE "WF_FORM_CONTRACTAPPROVED"
(
"ID" NUMBER NOT NULL,
"CONTRACTNUM" VARCHAR2(255),
"SUPERVISOR" VARCHAR2(255),
"SERVICECONTENT" VARCHAR2(255),
"CONTRACTDETAIL" VARCHAR2(255),
"NIGAO_DATE" DATETIME(6),
"TYPE" VARCHAR2(255),
"FORM_COMMON_ID" NUMBER,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR); 


comment on table WF_FORM_CONTRACTAPPROVED is '合同报批表';
comment on column WF_FORM_CONTRACTAPPROVED.ID is '主键';
comment on column WF_FORM_CONTRACTAPPROVED.CONTRACTNUM is '合同编号';
comment on column WF_FORM_CONTRACTAPPROVED.SUPERVISOR is '对方监事人';
comment on column WF_FORM_CONTRACTAPPROVED.SERVICECONTENT is '外购服务内容';
comment on column WF_FORM_CONTRACTAPPROVED.CONTRACTDETAIL is '合同明细';
comment on column WF_FORM_CONTRACTAPPROVED.NiGao_Date is '送审时间';
comment on column WF_FORM_CONTRACTAPPROVED.FORM_COMMON_ID is '通用表单的id';


INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF)
VALUES (110076, '合同报批', '合同报批', 14, 'contractapproved', 'xinhan', '1', null, null, null, null, null, null, null, null, null, null);


