
CREATE TABLE "WF_FORM_DRAFTAPPROVED"
(
"ID" NUMBER NOT NULL,
"TYPE" VARCHAR2(255),
"NIGAO_DATE" DATETIME(6),
"FORM_COMMON_ID" NUMBER,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR);


comment on table WF_FORM_DRAFTAPPROVED is '合同报批表';
comment on column WF_FORM_DRAFTAPPROVED.ID is '主键';
comment on column WF_FORM_DRAFTAPPROVED.TYPE is '文件类别';
comment on column WF_FORM_DRAFTAPPROVED.NiGao_Date is '拟稿时间';
comment on column WF_FORM_DRAFTAPPROVED.FORM_COMMON_ID is '通用表单的id';


INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF)
VALUES (110077, '委内文稿审核单', '委内文稿审核单', 14, 'draftapproved', 'xinhan', '1', null, null, null, null, null, null, null, null, null, null);


