
CREATE TABLE "WF_FORM_OTHERAPPROVED"
(
"ID" NUMBER NOT NULL,
"REQUEST_LEVEL" VARCHAR2(255),
"OPEN" VARCHAR2(6),
"REPORTING" VARCHAR2(255),
"TELE_PHONE" VARCHAR2(255),
"GROUP_DEPART" VARCHAR2(255),
"GROUP_NAME" VARCHAR2(255),
"VISIT_COUNTRY" VARCHAR2(255),
"VISIT_TIME" DATETIME(6),
"VISIT_PURPOSE" VARCHAR2(255),
"FAMILY_CONDITION" VARCHAR2(255),
"VISIT_ACOUNT" VARCHAR2(255),
"FORM_COMMON_ID" NUMBER,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR);


comment on table WF_FORM_OTHERAPPROVED is '外事报批表';
comment on column WF_FORM_OTHERAPPROVED.ID is '主键';
comment on column WF_FORM_OTHERAPPROVED.REQUEST_LEVEL is '请示等级';
comment on column WF_FORM_OTHERAPPROVED.OPEN is '公开';
comment on column WF_FORM_OTHERAPPROVED.REPORTING is '呈报处室';
comment on column WF_FORM_OTHERAPPROVED.TELE_PHONE is '分机号码';
comment on column WF_FORM_OTHERAPPROVED.GROUP_DEPART is '团体单位';
comment on column WF_FORM_OTHERAPPROVED.GROUP_NAME is '团体名称';
comment on column WF_FORM_OTHERAPPROVED.VISIT_COUNTRY is '出访地';
comment on column WF_FORM_OTHERAPPROVED.VISIT_TIME is '出访时间';
comment on column WF_FORM_OTHERAPPROVED.VISIT_PURPOSE is '出访时间';
comment on column WF_FORM_OTHERAPPROVED.FAMILY_CONDITION is '家属参团情况';
comment on column WF_FORM_OTHERAPPROVED.VISIT_ACOUNT is '出访经费';
comment on column WF_FORM_OTHERAPPROVED.FORM_COMMON_ID is '通用表单的id';


INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF)
VALUES (110075, '外事报批', '外事报批', 14, 'otherapproved', 'xinhan', '1', null, null, null, null, null, null, null, null, null, null);
