CREATE TABLE "WF_FORM_WORKAPPROVED"
(
"ID" NUMBER NOT NULL,
"RECEIVE_DOC_NUM" NUMBER,
"NI_GAO_DATA" DATETIME(6),
"TYPE" VARCHAR2(255),
"FORM_COMMON_ID" NUMBER,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR);


comment on table WF_FORM_WORKAPPROVED is '工作报批表';
comment on column WF_FORM_WORKAPPROVED.ID is '主键';
comment on column WF_FORM_WORKAPPROVED.RECEIVE_DOC_NUM is '收文文号';
comment on column WF_FORM_WORKAPPROVED.NI_GAO_DATA is '拟稿日期';
comment on column WF_FORM_WORKAPPROVED.FORM_COMMON_ID is '通用表单的id';


INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF)
VALUES (110074, '工作报批', '工作报批', 13, 'workapproved', 'xinhan', '1', null, null, null, null, null, null, null, null, null, null);
