[
 	//状态机最基本思想：先检查执行条件是否满足，如果满足，则执行业务方法；否则直接返回
	{
		"smDefId":"infoPublishWorkflow",//信息发布的工作流；
		//在接下来的groovy表达式中可以使用的bean的列表,默认包含
		//beanId:实体的id
		//paramBean:传入的bean参数；
		//currentUser当前用户；
		//smInfo:状态机信息
		//actionId:操作id
		//currentUser:当前用户
		"stateMachineBeans":["serviceUtils","coreInfoPublishService"],
	    "transitionList":[//一个bean的实例可以定义多个状态机，根据需求自行选择，如果参数中的stateMachineDefId为空，则使用default下的定义
	    	//saved
	        {
	    		"fromStateId":"saved","actionId":"read","toStateId":"saved",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.read(paramBean.id,currentUser)"
	    	},
	    	{
	    		"fromStateId":"saved","actionId":"publish","toStateId":"published",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')"
	    	},
	    	{
	    		"fromStateId":"saved","actionId":"update","toStateId":"saved",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.update(paramBean,currentUser)"
	    	},
	    	{
	    		"fromStateId":"saved","actionId":"delete","toStateId":"saved",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.delete(paramBean.id,currentUser)"
	    	},
	    	
	    	//published
	    	{
	    		"fromStateId":"published","actionId":"return","toStateId":"returned",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')"
	    	},
	    	{
	    		"fromStateId":"published","actionId":"read","toStateId":"published",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.read(paramBean.id,currentUser)"
	    	},
	    	{
	    		"fromStateId":"published","actionId":"delete","toStateId":"published",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.delete(paramBean.id,currentUser)"
	    	},
	    	
	    	//returned
	    	{
	    		"fromStateId":"returned","actionId":"republish","toStateId":"published",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')"
	    	},
	    	{
	    		"fromStateId":"returned","actionId":"read","toStateId":"returned",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.read(paramBean.id,currentUser)"
	    	},
	    	{
	    		"fromStateId":"returned","actionId":"update","toStateId":"returned",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.update(paramBean,currentUser)"
	    	},
	    	{
	    		"fromStateId":"returned","actionId":"delete","toStateId":"returned",
	    		"condition":"currentUser.permissionSet.contains('infoPublishMng')",
	    		"transitionMethod":"coreInfoPublishService.delete(paramBean.id,currentUser)"
	    	}
		],
	    "stateList":[
 	    	{"id":"saved","name":"暂存"},
 	    	{"id":"published","name":"已发布"},
 	    	{"id":"returned","name":"已撤销发布"}
 	    ],
 	    "actionList":[
 	        {"id":"read","name":"查看","type":"instance","icon":"fa-external-link"},
 	    	{"id":"publish","name":"发布","type":"instance","icon":"fa-external-link"},
 	    	{"id":"return","name":"撤销","type":"instance","icon":"fa-mail-reply-all"},
 	    	{"id":"republish","name":"重新发布","type":"instance","icon":"fa-external-link"},
 	    	{"id":"update","name":"编辑","type":"instance","icon":"fa-edit"},
 	    	{"id":"delete","name":"删除","type":"instance","icon":" fa-remove"}
 	    ]
	}
	
]