delete JYJ_CMS.INDEX_ICON where  1 =1;
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (1, 0, null, null, '中共上海市纪要局管理处', null, 'bg-0', 'fwgl', 1, null, null);
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (2, 0, null, null, '常用表单', 'menu.commonForms', 'bg-2', 'bgtnww', 2, 1, 'bt3.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (3, 0, null, null, '软件中心', 'menu.softwareCenter', 'bg-2', 'rjzx', 3, 1, 'bt5.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (4, 0, null, null, '留言板', 'menu.messageBoard', 'bg-2', 'lyb', 4, 1, 'ly.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (5, 0, null, null, '专家抽取', 'menu.expertExtraction', 'bg-2', 'zjcq', 1, 1, 'zj.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (6, 0, null, null, '局内通讯', 'menu.communication', 'bg-2', 'cywj', 5, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (7, 0, null, null, '值班表', 'menu.dutyWatch', 'bg-2', 'cywj', 6, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (8, 0, null, null, '密码综合管理', 'http://11.4.240.109:8088/jyjgl', 'bg-2', 'cywj', 6, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (9, 0, null, null, '区县平台', 'http://11.4.240.110:8088/jyjqxpt', 'bg-2', 'cywj', 6, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (10, 0, null, null, '设备评测', 'http://11.4.240.111:8088/jyjpc', 'bg-2', 'cywj', 6, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (11, 0, null, null, '内网门户', 'http://11.4.240.104:8088/jyjcms', 'bg-2', 'cywj', 6, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (12, 0, null, null, '协同办公', 'http://11.4.240.103:8088/jyjoa', 'bg-2', 'cywj', 6, 1, 'bt2.png');
INSERT INTO JYJ_CMS.INDEX_ICON (ID, ISDELETE, UPDATOR, UPDATETIME, ICONNAME, ICONURL, CLASSNAME, IMGNAME, ORDERNO, PARENTID, SHOW_IMAGE_NAME) VALUES (13, 0, null, null, '考勤', 'menu.attendance', 'bg-2', 'cywj', 5, 800, 'bt2.png');


delete from JYJ_CMS.INDEX_USER_ICON where 1=1;

INSERT INTO JYJ_CMS.INDEX_USER_ICON (ID, USERID, ORDERNO, ICONID)
select
"JYJ_CMS"."JXWOAUNIVERSALSEQ".NextVal, id, 1, 2
from "JYJ_CMS".ADMINISTRATOR;

INSERT INTO JYJ_CMS.INDEX_USER_ICON (ID, USERID, ORDERNO, ICONID)
select
"JYJ_CMS"."JXWOAUNIVERSALSEQ".NextVal, id, 2, 7
from "JYJ_CMS".ADMINISTRATOR;

INSERT INTO JYJ_CMS.INDEX_USER_ICON (ID, USERID, ORDERNO, ICONID)
select
"JYJ_CMS"."JXWOAUNIVERSALSEQ".NextVal, id, 3, 3
from "JYJ_CMS".ADMINISTRATOR;

INSERT INTO JYJ_CMS.INDEX_USER_ICON (ID, USERID, ORDERNO, ICONID)
select
"JYJ_CMS"."JXWOAUNIVERSALSEQ".NextVal, id, 4, 12
from "JYJ_CMS".ADMINISTRATOR;
