drop table EITC09.ORGUSER;
drop table EITC09.ORGDEPT;
drop table EITC09.ORGDU;
drop table EITC09.ORGGROUP;
drop table EITC09.ORGGU;
drop table EITC09.ORGPOST;
drop table EITC09.ORGPU;
drop table EITC09.ORGROLE;
drop table EITC09.ORGRU;
drop table EITC09.MPSMODULE;
drop table EITC09.MPSAVAILMODULE;


CREATE TABLE EITC09.ORGUSER (
  PKID          NUMBER, --	主键
  WORKCODE      VARCHAR2 (64), --
  SEQUENCEID    NUMBER, --
  USERNAME      VARCHAR2 (64), --	登录名
  PASSWORD      VARCHAR2 (64), --	密码密文
  NAME          VARCHAR2 (64), --	姓名
  GENDER        VARCHAR2 (10), --	性别
  LOGGINGON     NUMBER, --
  LOGGINGTIME   DATETIME, --	本次登录时间
  ONLEAVE       NUMBER, --
  TIMEOUT       NUMBER, --
  USERMODE      NUMBER, --	登录模式
  ALTERNATES    VARCHAR2 (64), --
  EMAIL         VARCHAR2 (64), --
  MOBILEPHONE   VARCHAR2 (64), --
  FLAG          NUMBER, --	是否可用
  GUI           NUMBER, --
  LASTLOGINIP   VARCHAR2 (64), --	上次登录地址
  LASTLOGINTIME DATETIME, --	上次登录时间
  PHOTOFILE_PATH VARCHAR2 (512), --原来是用另外一张表存储的CLOB字段，本次改造将把照片信息提出到文件系统中，数据库里面仅仅存储文件的路径
  PRIMARY KEY (PKID)
);


CREATE TABLE EITC09.ORGDEPT (
  PKID        NUMBER, --	原主键
  PARENTID    NUMBER, --	父结点
  SEQUENCEID  NUMBER, --	序号
  NAME        VARCHAR2 (64), --	名称
  BRIEF       VARCHAR2 (6), --	简称
  LOCATION    VARCHAR2 (32), --
  CONTACT     VARCHAR2 (32), --
  PRINCIPAL   VARCHAR2 (50), --
  DESCRIPTION VARCHAR2 (128), --
  FLAG        NUMBER, --	是否可用
  ORDERBY        NUMBER, --	是否可用
  PRIMARY KEY (PKID)
);

CREATE TABLE EITC09.ORGDU (
  DEPTID  NUMBER, --	部门主键
  USERID NUMBER, --	人员主键
  ORDERID NUMBER --	排序
  --FOREIGN KEY (DEPTID) REFERENCES ORGDEPT (ID),
  --FOREIGN KEY (USERID) REFERENCES ORGUSER (ID)
);

CREATE TABLE EITC09.ORGGROUP (
  PKID        NUMBER, --	主键
  PARENTID    NUMBER, --	父结点
  NAME        VARCHAR2 (64), --	组名称
  CONTACT     VARCHAR2 (64), --
  PRINCIPAL   VARCHAR2 (64), --
  DESCRIPTION VARCHAR2 (128), --
  FLAG        NUMBER, --	是否可用
  PRIMARY KEY (PKID)
);

CREATE TABLE EITC09.ORGGU (
  GROUPID NUMBER, --	组主键
  USERID  NUMBER --	人员主键
  --FOREIGN KEY (GROUPID) REFERENCES ORGGROUP (ID),
  --FOREIGN KEY (USERID) REFERENCES ORGUSER (ID)
);

CREATE TABLE EITC09.ORGPOST (
  PKID        NUMBER, --	主键
  DEPTID      NUMBER, --	部门主键
  NAME        VARCHAR2 (64), --	名称
  DESCRIPTION VARCHAR2 (128), --
  FLAG        NUMBER, --	是否可用
  ORDERBY     NUMBER,
  PRIMARY KEY (PKID)
  --FOREIGN KEY (DEPTID) REFERENCES ORGDEPT (ID)
);

CREATE TABLE EITC09.ORGPU (
  POSTID NUMBER, --	岗位主键
  USERID NUMBER, --	人员主键
  DEPTID NUMBER,  --	部门主键 暂时无效 岗位表已关联部门表
  DPUORDERBY  NUMBER  --排序字段
  --FOREIGN KEY (POSTID) REFERENCES ORGPOST (ID),
  --FOREIGN KEY (DEPTID) REFERENCES ORGDEPT (ID),
  --FOREIGN KEY (USERID) REFERENCES ORGUSER (ID)
);

CREATE TABLE EITC09.ORGROLE (
  PKID        NUMBER, --	主键
  NAME        VARCHAR2 (64), --	角色名称
  DESCRIPTION VARCHAR2 (128), --
  FLAG        NUMBER, --	是否可用
  PRIMARY KEY (PKID)
);

CREATE TABLE EITC09.ORGRU (
  ROLEID   NUMBER, --	角色主键
  USERID   NUMBER, --	人员主键
  PRIORITY NUMBER -- 
  --FOREIGN KEY (ROLEID) REFERENCES ORGROLE (ID),
  --FOREIGN KEY (USERID) REFERENCES ORGUSER (ID)
);


CREATE TABLE EITC09.MPSMODULE (
  PKCODE      VARCHAR2 (128), --	原主键,用的varchar
  TITLE       VARCHAR2 (50), --	模块标题
  ICON        VARCHAR2 (128), --图标
  ACTIONURL   VARCHAR2 (128), --相对URL
  TARGETFRAME VARCHAR2 (512),
  DESCRIPTION VARCHAR2 (512),
  FLAG  VARCHAR2 (10), 
  ICONFOCUS  VARCHAR2 (128),
  ICONSELECT  VARCHAR2 (128),
  PARENTID    NUMBER, --	父结点
  PRIMARY KEY (PKCODE)
);


CREATE TABLE EITC09.MPSAVAILMODULE (
  ELEMENTID      NUMBER, --	表示授权对象的ID，按照elementid所指示的对象类型，表示人员、角色、部门、岗位表中一个对象的ID
  ELEMENTTYPE    VARCHAR2 (50), --	范围（U,R,D,P） 表示授权的对象类型是 人员（U）角色（R）部门（D）岗位（P）
  MODULECODE     NUMBER, --mpsmodule表内一个对象的主键值
  FLAG           VARCHAR2 (10),
  PRIMARY KEY (ELEMENTID,ELEMENTTYPE,MODULECODE)
);
