INSERT INTO PROCESS_DEF_GROUP (ID, FORM_EN_NAME, FORM_ZH_NAME, DESCRIPTION, FLAG, ORDER_NUM)
VALUES (6, 'huiyi', '会议', null, '1', 6);

INSERT INTO WF_PROCESS_FORM (ID, FORM_EN_NAME, FORM_ZH_NAME, DESCRIPTION, BELONG_GROUP, FLAG, ORDER_NUM)
VALUES (14, 'jxwhuiyi', '长城电子会议', '长城电子会议', 'huiyi', '1', null);

INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF)
VALUES (888888, '长城电子会议', '长城电子会议', 14, 'jxwhuiyi', 'huiyi', '1', null, null, null, null, null, null, null, null, null, null);


INSERT INTO WF_PROCESS_DEF_VERSION (ID, PROCESS_DEF_ID, VERSION, FILE_NAME, FILE_PATH, IS_ACTIVE, DESCRIPTION) VALUES (110126, 888888, 1, '12a44a47-34f6-4277-8071-40ed377d03e1', '12a44a47-34f6-4277-8071-40ed377d03e1.xml', '1', '长城电子会议');





---------20190122---------------
INSERT INTO WF_PROCESS_FORM (ID, FORM_EN_NAME, FORM_ZH_NAME, DESCRIPTION, BELONG_GROUP, FLAG, ORDER_NUM)
VALUES (20, 'meeting', '会议', '会议管理', 'huiyi', '1', null);

INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF)
VALUES (888894, '会议', '会议管理', 14, 'meeting', 'huiyi', '1', null, null, null, null, null, null, null, null, null, null);

INSERT INTO WF_PROCESS_DEF_VERSION (ID, PROCESS_DEF_ID, VERSION, FILE_NAME, FILE_PATH, IS_ACTIVE, DESCRIPTION) VALUES (110127, 888894, 1, 'bdf93694-ebd9-4ac4-9edc-760df4f55728', 'bdf93694-ebd9-4ac4-9edc-760df4f55728.xml', '1', '机要秘书会议登录')