alter table MPSMODULE modify NG_STATE varchar2(125);

/*行政*/
update  MPSMODULE set parentid=100125,flag=1,NG_STATE='coreHome.categoryMaintenance:administrative',ACTIONURL='/coreHome/categoryMaintenance/administrative' where id=100130;


/*党委*/
update  MPSMODULE set parentid=100131,flag=1,NG_STATE='coreHome.categoryMaintenance:partyCommittee',ACTIONURL='/coreHome/categoryMaintenance/partyCommittee' where id=100136;

update  MPSMODULE set flag=1,NG_STATE='coreHome.' where title like '%办公用品';





CREATE TABLE "WF_FORM_JXWDWHYJY"
(
"ID" NUMBER NOT NULL,
"SEND_TO_MAIN" VARCHAR2(512),
"SEND_TO_CC" VARCHAR2(512),
"HE_GAO" VARCHAR2(512),
"HUI_GAO" VARCHAR2(512),
"HUI_QIAN" VARCHAR2(512),
"SHEN_HE" VARCHAR2(512),
"QIAN_FA" VARCHAR2(512),
"THEME" VARCHAR2(512),
"NI_GAO_USERNAME" VARCHAR2(255),
"NI_GAO_DATE" DATETIME(6),
"FORM_COMMON_ID" NUMBER,
"ZHU_SONG_NUM" NUMBER,
"CHAO_SONG_NUM" NUMBER,
"ZHI_NENG_CHU_SHI_NUM" NUMBER,
"GUI_DANG_NUM" NUMBER,
"OTHER_NUM" NUMBER,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;
COMMENT ON TABLE "WF_FORM_JXWDWHYJY" IS '党委会议纪要发文';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."CHAO_SONG_NUM" IS '抄送份数';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."FORM_COMMON_ID" IS '通用表单的id';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."GUI_DANG_NUM" IS '归档份数';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."HE_GAO" IS '核稿';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."HUI_GAO" IS '会稿';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."HUI_QIAN" IS '会签';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."ID" IS '主键';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."NI_GAO_DATE" IS '拟稿年月日';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."NI_GAO_USERNAME" IS '拟稿人';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."OTHER_NUM" IS '其他份数';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."QIAN_FA" IS '签发';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."SEND_TO_CC" IS '抄送';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."SEND_TO_MAIN" IS '主送';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."SHEN_HE" IS '审核';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."THEME" IS '主题词';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."ZHI_NENG_CHU_SHI_NUM" IS '职能处室份数';
COMMENT ON COLUMN "WF_FORM_JXWDWHYJY"."ZHU_SONG_NUM" IS '主送份数';
