update ORGUSER set USERMODE = '1', PWD_BAC = '29E7162480A4D5F8417A2BB8CC41CA7062DB4FB57018E2D1CF13ADAB36D09E21' where 1=1;

update WF_PROCESS_INSTANCE set WNGK = '是' where WNGK is null;

alter table WF_PROCESS_INSTANCE add (DOC_YEAR number) ;
alter table WF_PROCESS_INSTANCE add (DOC_NUMBER number);
COMMENT ON COLUMN WF_PROCESS_INSTANCE."DOC_YEAR" IS '年份';
COMMENT ON COLUMN WF_PROCESS_INSTANCE."DOC_NUMBER" IS '文号';

update WF_PROCESS_INSTANCE i set i.DOC_YEAR =c.DOC_YEAR,i.DOC_NUMBER =c.DOC_NUMBER from WF_FORM_COMMON c where  i.ID = c.PRO_INST_ID;
select c.DOC_NUMBER,c.DOC_YEAR,i.DOC_NUMBER,i.DOC_YEAR from WF_PROCESS_INSTANCE i inner join WF_FORM_COMMON c on  i.ID = c.PRO_INST_ID where i.TITLE ='标题已ok'  ;

CREATE or replace INDEX wpi_idx_ct  ON wf_process_instance (DOC_YEAR desc,DOC_NUMBER desc , pro_def_group_id,FORM_DEF_ID);
