alter table WF_OPINION add (SHOW_FIELD VARCHAR2(20));
COMMENT ON COLUMN WF_OPINION.SHOW_FIELD IS '意见展示字段';
update WF_OPINION set SHOW_FIELD = 'normal';


UPDATE WF_FORM_ACTION SET ACTION_ID = 'relationReciveDoc', NAME = '关联收文', DESCRIPTION = '审批单：关联收文', PRE_CONDITION = ' $scope.fc.wpsDetail.middleContentType==''form''  && SysUtils.notEmpty($scope.task.theCommonFormInfo,[''belongProInst'',''relatedReceiveDocId''])', ACTION_TO_PERFORM = '$scope.fc.relationReciveDoc(''relatedReceiveDocIdDialog'',''relatedReceiveDocId'')', IMAGE_URL = 'images/sidebar_right-glsw.svg', ORDER_NUM = 250, FLAG = '1', ACTION_TYPE = 'currentTaskDeal' WHERE ID = 13;
UPDATE WF_FORM_ACTION SET ACTION_ID = 'associatedFile', NAME = '关联发文', DESCRIPTION = '审批单：关联发文', PRE_CONDITION = ' $scope.fc.wpsDetail.middleContentType==''form''  && SysUtils.notEmpty($scope.task.theCommonFormInfo,[''belongProInst'',''relatedReceiveDocId''])', ACTION_TO_PERFORM = '$scope.fc.relationReciveDoc(''relatedReceiveDocIdDialog'',''relatedReceiveDocId'')', IMAGE_URL = 'images/sidebar_right-glsw.svg', ORDER_NUM = 251, FLAG = '1', ACTION_TYPE = 'currentTaskDeal' WHERE ID = 26;
UPDATE WF_FORM_ACTION SET ACTION_ID = 'associatedFileHistory', NAME = '关联发文', DESCRIPTION = '审批单：关联发文', PRE_CONDITION = ' $scope.fc.wpsDetail.middleContentType==''form''  && SysUtils.notEmpty($scope.task.theCommonFormInfo,[''belongProInst'',''relatedReceiveDocId''])', ACTION_TO_PERFORM = '$scope.fc.relationReciveDoc(''relatedReceiveDocIdDialog'',''relatedReceiveDocId'')', IMAGE_URL = 'images/sidebar_right-glsw.svg', ORDER_NUM = 251, FLAG = '1', ACTION_TYPE = 'hisView' WHERE ID = 27;
UPDATE WF_FORM_ACTION SET ACTION_ID = 'relateDuWenHistory', NAME = '关联督文', DESCRIPTION = '审批单：关联督文', PRE_CONDITION = '$scope.fc.wpsDetail.middleContentType==''form'' && SysUtils.notEmpty($scope.task.theCommonFormInfo,[''belongProInst'',''relateDuWenDocId''])', ACTION_TO_PERFORM = '$scope.fc.relationReciveDoc(''relatedReceiveDocIdDialog'',''relateDuWenDocId'')', IMAGE_URL = 'images/sidebar_right-glsw.svg', ORDER_NUM = 252, FLAG = '1', ACTION_TYPE = 'hisView' WHERE ID = 50;
UPDATE WF_FORM_ACTION SET ACTION_ID = 'relateDuWen', NAME = '关联督文', DESCRIPTION = '审批单：关联督文', PRE_CONDITION = '$scope.fc.wpsDetail.middleContentType==''form''&& $scope.task.status==''Accepted'' && SysUtils.notEmpty($scope.task.theCommonFormInfo,[''belongProInst'',''relateDuWenDocId''])', ACTION_TO_PERFORM = '$scope.fc.relationReciveDoc(''relatedReceiveDocIdDialog'',''relateDuWenDocId'')', IMAGE_URL = 'images/sidebar_right-glsw.svg', ORDER_NUM = 252, FLAG = '1', ACTION_TYPE = 'currentTaskDeal' WHERE ID = 51;
UPDATE WF_FORM_ACTION SET ACTION_ID = 'HisAssociatedShouWen', NAME = '关联收文', DESCRIPTION = '审批单：关联收文', PRE_CONDITION = '$scope.fc.wpsDetail.middleContentType==''form'' && SysUtils.notEmpty($scope.task.theCommonFormInfo,[''belongProInst'',''relatedReceiveDocId''])', ACTION_TO_PERFORM = '$scope.fc.relationReciveDoc(''relatedReceiveDocIdDialog'',''relatedReceiveDocId'')', IMAGE_URL = 'images/sidebar_right-glsw.svg', ORDER_NUM = 250, FLAG = '1', ACTION_TYPE = 'hisView' WHERE ID = 759478;
