{
	"id":"fawenDef",
	"name":"发文流程定义",
	"description":"发文的描述",
	"createDate":"2018-01-24",
	"updateDate":"2018-01-24",
	"creatorId":"lq",
	"creatorName":"刘强",
	"nodes":[
	    {
		   "id":"ni_gao",
		   "name":"拟稿",
		   "isInitNode":true,
		   "isAccept":true,
		   "candidateType":"All",//所有部门
		   "candidateExp":null,
		   "assigneeType":"SinglePerson",
		   "execType":null,
		   "operations":[
		       {
		    	   "id":"to_he_gao",
		    	   "name":"核稿",
		    	   "targetNodeId":"he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       }  
		   ]
	    },
	    {
		   "id":"he_gao",
		   "name":"核稿",
		   "candidateType":"SingleDepart",//候选参与者类型：单个部门
		   "candidateExp":"currentUser.getDepartment().getId()",//当前用户所属的部门
		   "assigneeType":"SinglePerson",
		   "execType":null,
		   "operations":[
		       {
		    	   "id":"to_hui_gao",
		    	   "name":"会稿",
		    	   "targetNodeId":"hui_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },  
		       {
		    	   "id":"to_ni_gao",
		    	   "name":"拟稿",//如果是送回拟稿，则只能退至拟稿人
		    	   "targetNodeId":"ni_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_zhuan_zhi_he_gao",
		    	   "name":"专职核稿",
		    	   "targetNodeId":"zhuan_zhi_he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_he_gao",
		    	   "name":"核稿",
		    	   "targetNodeId":"he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       }
		   ]
	    },
	    {
		   "id":"hui_gao",
		   "name":"会稿",
		   "candidateType":"ListOfDepart",//候选参与者类型：部门列表
		   "candidateExp":"'3,5,6'",//办公室、综合规划处、经济运行处
		   "assigneeType":"SinglePerson",
		   "execType":null,
		   "operations":[
		       {
		    	   "id":"to_he_gao",
		    	   "name":"核稿",
		    	   "targetNodeId":"he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_zhuan_zhi_he_gao",
		    	   "name":"专职核稿",
		    	   "targetNodeId":"zhuan_zhi_he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_hui_gao",
		    	   "name":"会稿",
		    	   "targetNodeId":"hui_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       }
		   ]
	    },
	    {
		   "id":"zhuan_zhi_he_gao",
		   "name":"专职核稿",
		   "candidateType":"SingleRole",//候选参与者类型：角色
		   "candidateExp":"'82'",//专职核稿
		   "assigneeType":"SinglePerson",
		   "execType":null,
		   "operations":[
		       {
		    	   "id":"to_hui_gao",
		    	   "name":"会稿",
		    	   "targetNodeId":"hui_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_he_gao",
		    	   "name":"核稿",
		    	   "targetNodeId":"he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_shen_he",
		    	   "name":"审核",
		    	   "targetNodeId":"shen_he",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_zhuan_zhi_he_gao",
		    	   "name":"专职核稿",
		    	   "targetNodeId":"zhuan_zhi_he_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       } 
		   ]
	    },
	    {
		   "id":"shen_he",
		   "name":"审核",
		   "candidateType":"ListOfPost",//候选参与者类型：岗位列表
		   "candidateExp":"'2,5'",//办公室主任和副主任
		   "assigneeType":"SinglePerson",//
		   "execType":null,
		   "operations":[
		       {
		    	   "id":"to_shen_qian",
		    	   "name":"审签",
		    	   "targetNodeId":"shen_qian",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_hui_gao",
		    	   "name":"会稿",
		    	   "targetNodeId":"hui_gao",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       },
		       {
		    	   "id":"to_shen_he",
		    	   "name":"会稿",
		    	   "targetNodeId":"shen_he",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       } 
		   ]
	    },
	    {
		   "id":"shen_qian",
		   "name":"审签",
		   "candidateType":"ListOfDepart",//候选参与者类型：单位列表
		   "candidateExp":"'75,84'",//长城电子党委领导,长城电子领导
		   "assigneeType":"SinglePerson",//
		   "execType":null,
		   "operations":[
			   {
				   "id":"to_fa_wen_deng_lu",
				   "name":"发文登录",
				   "targetNodeId":"fa_wen_deng_lu",
				   "preCondition":"true",
				   "postLogic":null
			   }, 
		       {
		    	   "id":"to_shen_qian",
		    	   "name":"审签",
		    	   "targetNodeId":"shen_qian",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       }
		   ]
	    },
	    {
		   "id":"fa_wen_deng_lu",
		   "name":"发文登录",
		   "candidateType":"SingleRole",//类型：角色
		   "candidateExp":"'2'",//发文登录角色
		   "assigneeType":"SinglePerson",//
		   "execType":null,
		   "operations":[
			   {
				   "id":"to_pai_ban",
				   "name":"排版",
				   "targetNodeId":"pai_ban",
				   "preCondition":"true",
				   "postLogic":null
			   }, 
		       {
		    	   "id":"to_shen_qian",
		    	   "name":"审签",
		    	   "targetNodeId":"shen_qian",
		    	   "preCondition":"true",
		    	   "postLogic":null
		       }
		   ]
	    },
	    {
		   "id":"pai_ban",
		   "name":"排版",
		   "candidateType":"SingleRole",//类型：角色
		   "candidateExp":"'3'",//文印角色
		   "assigneeType":"SinglePerson",//
		   "execType":null,
		   "operations":[
			   {
				   "id":"to_qian_zhang",
				   "name":"签章",
				   "targetNodeId":"qian_zhang",
				   "preCondition":"true",
				   "postLogic":null
			   }
		   ]
	    },
	    {
		   "id":"qian_zhang",
		   "name":"签章",
		   "candidateType":"SingleRole",//类型：角色
		   "candidateExp":"'2'",//发文登录角色
		   "assigneeType":"SinglePerson",//
		   "execType":null,
		   "operations":[
			   {
				   "id":"to_wen_yin",
				   "name":"文印",
				   "targetNodeId":"wen_yin",
				   "preCondition":"true",
				   "postLogic":null
			   },
			   {
				   "id":"to_pai_ban",
				   "name":"排版",
				   "targetNodeId":"pai_ban",
				   "preCondition":"true",
				   "postLogic":null
			   },
			   {
				   "id":"to_qian_zhang",
				   "name":"签章",
				   "targetNodeId":"qian_zhang",
				   "preCondition":"true",
				   "postLogic":null
			   }
		   ]
	    },
	    {
		   "id":"wen_yin",
		   "name":"文印",
		   "candidateType":"SingleRole",//类型：角色
		   "candidateExp":"'3'",//文印角色
		   "assigneeType":"SinglePerson",//
		   "execType":null,
		   "operations":[
			   {
				   "id":"to_qian_zhang",
				   "name":"签章",
				   "targetNodeId":"qian_zhang",
				   "preCondition":"true",
				   "postLogic":null
			   }
		   ]
	    }
	]
}
