alter table WF_CURRENT_TASK_INFO add (ACCETP_TIME datetime(6));
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.ACCETP_TIME IS '任务接收时间';

alter table WF_HISTORY_TASK_INFO add (ACCETP_TIME datetime(6));
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.ACCETP_TIME IS '任务接收时间';
alter table WF_HISTORY_TASK_INFO add (TASK_CREATE_TIME datetime(6));
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.TASK_CREATE_TIME IS '保留任务创建时间用于历史查看排序'
alter table WF_HISTORY_TASK_INFO add (TASK_HIS_SHOW_TAG varchar2(20));
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.TASK_HIS_SHOW_TAG IS '用于查看流程';
alter table WF_HISTORY_TASK_INFO add (TASK_HIS_SHOW_STATUS varchar2(20));
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.TASK_HIS_SHOW_STATUS IS '查看流程里显示状态';

commit