UPDATE MPSMODULE SET FLAG = '1', ICON = 'treeview_1' WHERE TITLE = '办公管理';
UPDATE MPSMODULE SET FLAG = '1',TARGETFRAME = 'shouwenManage',ACTIONURL = '/rCurrentTaskInfo/getTodoList' WHERE TITLE = '收文管理';
UPDATE MPSMODULE SET FLAG = '1',TARGETFRAME = 'fawenManage',ACTIONURL = '/rCurrentTaskInfo/getTodoList' WHERE TITLE = '发文管理';

COMMIT ;


-- SELECT TARGETFRAME,COUNT(*) FROM MPSMODULE GROUP BY TARGETFRAME;
-- SELECT * FROM MPSMODULE WHERE TITLE = '收文管理';
-- SELECT * FROM MPSMODULE WHERE TITLE = '办公管理';
-- SELECT * FROM MPSMODULE WHERE TITLE = '配置人员';
-- SELECT * FROM MPSMODULE WHERE TITLE = '删除';
-- SELECT * FROM MPSMODULE WHERE TARGETFRAME = 'parent.MPBiz';


