
UPDATE MPSMODULE SET ICON = 'treeview_2',FLAG = '0';

UPDATE MPSMODULE SET FLAG = '1'  WHERE TITLE = '系统';
UPDATE MPSMODULE SET FLAG = '1'  WHERE TITLE = '项目资金';
UPDATE MPSMODULE SET FLAG = '1'  WHERE TITLE = '事务';
UPDATE MPSMODULE SET FLAG = '1'  WHERE TITLE = '办公';

UPDATE MPSMODULE SET FLAG = '1', ICON = 'treeview_1' WHERE TITLE = '个人秘书';
UPDATE MPSMODULE SET FLAG = '1',TARGETFRAME = 'todoList',ACTIONURL = '/rCurrentTaskInfo/getTodoList' WHERE TITLE = '待办事宜';

UPDATE MPSMODULE SET FLAG = '1', ICON = 'treeview_2' WHERE TITLE = '组织管理';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'userManageList',ACTIONURL = '/coreUser/searchUser' WHERE TITLE = '人员';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'departManageList',ACTIONURL = '/coreDepartment/departmentTree' WHERE TITLE = '部门';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'roleManageList',ACTIONURL='/coreRole/listTopClick' WHERE TITLE = '角色';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'postManageList',ACTIONURL='/coreDepartment/deptMixPostTree' WHERE TITLE = '岗位';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'groupManageList',ACTIONURL='/coreGroup/groupTree' WHERE TITLE = '组';

UPDATE MPSMODULE SET FLAG = '1', ICON = 'treeview_3' WHERE TITLE = '权限管理';
UPDATE MPSMODULE  SET FLAG = '1', TARGETFRAME = 'moduleAuthManageList',ACTIONURL='/coreMpsavailModule/init' WHERE TITLE = '模块授权';

UPDATE MPSMODULE  SET FLAG = '1', ICON = 'treeview_4' WHERE TITLE = '流程管理';
UPDATE MPSMODULE  SET FLAG = '1', TARGETFRAME = 'processDefList',ACTIONURL='/processDefManage/list' WHERE TITLE = '流程定制';

UPDATE MPSMODULE SET FLAG = '1', ICON = 'treeview_4' WHERE TITLE = '字典管理';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'dicManage',ACTIONURL='/dicCategory/list' WHERE TITLE = '系统字典';

UPDATE MPSMODULE SET FLAG = '1', ICON = 'treeview_5' WHERE TITLE = '运行管理';
UPDATE MPSMODULE SET FLAG = '1', TARGETFRAME = 'auditInfoList',ACTIONURL='/auditInfo/list' WHERE TITLE = '日志管理';


COMMIT ;




-- SELECT TARGETFRAME,COUNT(*) FROM MPSMODULE GROUP BY TARGETFRAME;
--
--
-- SELECT * FROM MPSMODULE WHERE TITLE = '权限管理';
-- SELECT * FROM MPSMODULE WHERE TITLE = '运行管理';
-- SELECT * FROM MPSMODULE WHERE TITLE = '配置人员';
-- SELECT * FROM MPSMODULE WHERE TITLE = '删除';
-- SELECT * FROM MPSMODULE WHERE TARGETFRAME = 'parent.MPBiz';


