DROP TABLE WF_PROCESS_INSTANCE;
DROP TABLE WF_CURRENT_TASK_INFO;
DROP TABLE WF_HISTORY_TASK_INFO;
DROP TABLE WF_PROCESS_DEF_MANAGE;
DROP TABLE WF_PROCESS_DEF_VERSION;
DROP TABLE WF_FORM_COMMON;

DROP TABLE WF_FORM_FAWEN;
DROP TABLE WF_FORM_JXWSHOUWEN;
DROP TABLE WF_FORM_JXWSJSHOUWEN;
DROP TABLE WF_FORM_JXWXINHAN;
DROP TABLE WF_FORM_JXWDWSHOUWEN;
DROP TABLE WF_FORM_JXWDWFAWEN;

CREATE TABLE WF_PROCESS_INSTANCE (
  ID                 NUMBER, --	主键
  CURRENT_NODE_ID    VARCHAR2(255), --当前所处节点的i
  CREATOR_ID         NUMBER, --创建流程的用户的id
  CREATOR_NAME       VARCHAR2(50), --创建流程的用户名称
  CREATE_TIME        DATETIME, --创建时间
  LAST_UPDATED_TIME  DATETIME, --最新流转时间,
  PROCESS_VERSION_ID NUMBER, --流程定义的版本信息
  FORM_COMMON_ID     NUMBER,
  FORM_DEF_ID        VARCHAR2(255), --个性化表单定义的的id,
  FORM_DETAIL_ID     NUMBER, --个性化表单实例的id,
  PRIMARY KEY (ID)
);

CREATE TABLE WF_CURRENT_TASK_INFO (
  ID                NUMBER, --	主键
  PRO_INST_ID       NUMBER, -- 当前任务所属流程实例的id
  ASSIGNEE          NUMBER, --接收人的id
  STATUS            VARCHAR2(50), --任务的状态：未接收、已接收、已办结；
  CREATOR_ID        NUMBER, --创建流程的用户的id
  CREATOR_NAME      VARCHAR2(50), --创建流程的用户名称
  CREATE_TIME       DATETIME, --创建时间
  LAST_UPDATED_TIME DATETIME, --最新流转时间
  TASK_TYPE         VARCHAR2(255), --任务类型
  ASSIGNEE_TYPE     VARCHAR2(255), --接收者类型
  PRIMARY KEY (ID)
);


CREATE TABLE WF_HISTORY_TASK_INFO (
  ID                   NUMBER, --	主键
  PRO_INST_ID          NUMBER, -- 任务所属流程实例的id
  FROM_NODE_ID         VARCHAR2(255), --开始节点
  TO_NODE_ID           VARCHAR2(255), --目标节点
  OPERATE_TIME         DATETIME, --操作时间
  OPERATOR_ID          NUMBER, --操作人员id
  OPERATOR_NAME        VARCHAR2(255), --操作人员姓名；
  OPERATOR_DEPART_ID   NUMBER, --操作人员所属部门；
  OPERATOR_DEPART_NAME VARCHAR2(50), --操作人员所属部门名称；
  OPINION              VARCHAR2(512), --操作意见 冗余字段 意见放入个性表单相关字段

  FROM_NODE_NAME       VARCHAR2(255),
  TO_NODE_NAME         VARCHAR2(255),
  TASK_TYPE            VARCHAR2(255),
  PRIMARY KEY (ID)
);




CREATE TABLE WF_PROCESS_DEF_MANAGE (
  ID          NUMBER, --	主键
  NAME        VARCHAR2(255), --流程定义的name;
  DESCRIPTION VARCHAR2(1024), --流程定义的描述
  ORDER_NUM   NUMBER, --排序字段
  FORM_DEF_ID VARCHAR2(255),
  PRIMARY KEY (ID)
);





CREATE TABLE WF_PROCESS_DEF_VERSION (
  ID             NUMBER, --	主键
  PROCESS_DEF_ID NUMBER, --外键，流程定义的id;
  VERSION        NUMBER, --版本号
  FILE_NAME      VARCHAR2(255), --文件名
  FILE_PATH      VARCHAR2(1024),
  IS_ACTIVE      VARCHAR2(10), --是否启用
  DESCRIPTION    VARCHAR2(1024), --描述
  PRIMARY KEY (ID)
);




CREATE TABLE WF_FORM_COMMON (
  ID               NUMBER, --	主键
  EMERGENCE_LEVEL  VARCHAR2(64), --紧急程度：待字典描述;  通用字段；
  PUBLICITY_LEVEL  VARCHAR2(64), --公开级别：委内公开，主动公开，不予公开，依申请公开；  通用字段；
  DOC_TYPE         VARCHAR2(255), --文种；通用字段；
  SECRET_FORM_ID   NUMBER, --定密单ID
  SECRET_LEVEL     VARCHAR2(255), --密级；冗余 通用字段；
  DEPT_ID          NUMBER, --流程发起部门 用于页面展示部门简称
  DOC_YEAR         INTEGER, --年份；通用字段；
  DOC_NUMBER       INTEGER, --号；通用字段；
  TITLE            VARCHAR2(512), --标题；通用字段；
  NOT_OPEN_REASON  VARCHAR2(64), --不予公开理由：国家秘密，个人隐私，内部管理信息，商业秘密，危及三安全一稳定，过程性信息，其他理由；通用字段
  OTHER_REASON     VARCHAR2(255), --不予公开的其他理由；通用字段
  NUMBER_OF_COPY   INTEGER, --打印份数；通用字段
  FORM_DETAIL_ID   NUMBER, --个性表单记录的id;
  FORM_DETAIL_TYPE VARCHAR2(64), --个性表单的类型
  DEPART_NAME      VARCHAR2(255),
  DOC_PREFIX       VARCHAR2(50),
  DOC_FULL_NAME    VARCHAR2(255),
  PRIMARY KEY (ID)
);


--1.长城电子发文
CREATE TABLE WF_FORM_FAWEN (
  ID                     NUMBER, --	主键
  RELATED_RECEIVE_DOC_ID NUMBER, --关联收文号；个性字段；
  SEND_TO_MAIN           VARCHAR2(512), --主送；个性字段；
  SEND_TO_CC             VARCHAR2(512), --抄送；个性字段；
  HE_GAO                 VARCHAR2(512), --核稿；个性字段；
  HUI_GAO                VARCHAR2(512), --会稿；个性字段；
  HUI_QIAN               VARCHAR2(512), --会签；个性字段；
  SHEN_HE                VARCHAR2(512), --审核；个性字段；
  QIAN_FA                VARCHAR2(512), --签发；个性字段；
  NI_GAO_USERID          NUMBER, --拟稿人id；个性字段；
  NI_GAO_USERNAME        VARCHAR2(64), --拟稿人姓名，冗余字段；个性字段；
  NI_GAO_DATE            DATETIME, --拟稿年月日；个性字段；
  FORM_COMMON_ID         NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);



--2.长城电子收文
CREATE TABLE WF_FORM_JXWSHOUWEN (
  ID                  NUMBER, --	主键
  INCOMING_DOC_DEPART VARCHAR2(512), --来文单位
  INCOMING_DOC_NUM    VARCHAR2(512), --来文文号
  INCOMING_NUM        NUMBER, --来文份数
  RECEIVE_DATE        DATETIME, --收文日期
  RECEIVE_DOC_NUM     NUMBER, --收文文号
  LEADER_OPINION      VARCHAR2(1024), --领导批示
  TODO_OPINION        VARCHAR2(1024), --拟办意见
  NI_BAN              VARCHAR2(1024), --拟办
  NI_GAO_DATA         DATETIME, -- 拟稿日期
  SHEN_HE             VARCHAR2(1024), --审核
  SHEN_HE_DATE        DATETIME, --审核日期
  FORM_COMMON_ID      NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);




--3.长城电子上级来文收文
CREATE TABLE WF_FORM_JXWSJSHOUWEN (
  ID                  NUMBER, --	主键
  RECEIVE_SERIAL_NUM  VARCHAR2(512), --收文编号
  RECEIVE_DATE        DATETIME, --收文日期
  INCOMING_NUM        NUMBER, --收文分数
  INCOMING_ZI_HAO     VARCHAR2(512), --来文字号；
  INCOMING_DOC_DEPART VARCHAR2(512), --来文单位；
  ATTACH_DESC         VARCHAR2(512), --附件说明
  READ_OPINION        VARCHAR2(1024), --阅示意见
  TODO_OPINION        VARCHAR2(1024), --办理意见
  REGISTER_USER       VARCHAR2(255), --登记人
  REGISTER_DATE       DATETIME, --登记时间
  FORM_COMMON_ID      NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);




--4.长城电子信函收文
CREATE TABLE WF_FORM_JXWXINHAN (
  ID                  NUMBER, --	主键
  INCOMING_DOC_DEPART VARCHAR2(512), --来文单位；
  INCOMING_DOC_NUM    VARCHAR2(512), --来文文号
  RECEIVE_DATE        DATETIME, --收到日期；
  DOC_TYPE            VARCHAR2(255), --类别,
  RECEIVE_DOC_NUM     NUMBER, --收文文号；
  DOC_ABSTRACT        VARCHAR2(512), --摘要
  LIUZHUAN_OPINION    VARCHAR2(512), --流转意见
  RECEIVE_USER        VARCHAR2(255), -- 收件人
  SHOUJIAN_DATE       DATETIME, -- 收件时间
  AUDIT_USER          VARCHAR2(255), --审核人
  FORM_COMMON_ID      NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);



--5.长城电子党委收文
CREATE TABLE WF_FORM_JXWDWSHOUWEN (
  ID                  NUMBER, --	主键
  INCOMING_DOC_DEPART VARCHAR2(512), --来文单位；
  INCOMING_DOC_NUM    VARCHAR2(512), --来文文号
  INCOMING_NUM        NUMBER, --来文份数；个性字段；
  RECEIVE_DATE        DATETIME, --收文日期；
  RECEIVE_DOC_NUM     VARCHAR2(512), --收文文号；
  LEADER_OPINION      VARCHAR2(1024), --领导批示
  TODO_OPINION        VARCHAR2(1024), --拟办意见
  NI_BAN              VARCHAR2(1024), --拟办
  NI_GAO_DATA         DATETIME, -- 拟稿日期
  SHEN_HE             VARCHAR2(1024), --审核
  SHEN_HE_DATE        DATETIME, --审核日期
  FORM_COMMON_ID      NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);




--6.长城电子党委发文
CREATE TABLE WF_FORM_JXWDWFAWEN (
  ID                     NUMBER, --	主键
  RELATED_RECEIVE_DOC_ID NUMBER, --关联收文号；
  SEND_TO_MAIN           VARCHAR2(512), --主送；
  SEND_TO_CC             VARCHAR2(512), --抄送；
  HE_GAO                 VARCHAR2(512), --核稿；
  HUI_GAO                VARCHAR2(512), --会稿；
  HUI_QIAN               VARCHAR2(512), --会签；
  SHEN_HE                VARCHAR2(512), --审核；
  QIAN_FA                VARCHAR2(512), --签发；
  THEME                  VARCHAR2(512), --主题词；
  NI_GAO_USERNAME        VARCHAR2(255), --拟稿人；
  NI_GAO_DATE            DATETIME, --拟稿年月日；
  FORM_COMMON_ID         NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);


--7.国防科工办发文
CREATE TABLE WF_FORM_GFKGBFAWEN (
  ID                     NUMBER, --	主键
  RELATED_RECEIVE_DOC_ID NUMBER, --关联收文号；个性字段；
  SEND_TO_MAIN           VARCHAR2(512), --主送；个性字段；
  SEND_TO_CC             VARCHAR2(512), --抄送；个性字段；
  HE_GAO                 VARCHAR2(512), --核稿；个性字段；
  HUI_GAO                VARCHAR2(512), --会稿；个性字段；
  HUI_QIAN               VARCHAR2(512), --会签；个性字段；
  SHEN_HE                VARCHAR2(512), --审核；个性字段；
  QIAN_FA                VARCHAR2(512), --签发；个性字段；
  NI_GAO_USERID          NUMBER, --拟稿人id；个性字段；
  NI_GAO_USERNAME        VARCHAR2(64), --拟稿人姓名，冗余字段；个性字段；
  NI_GAO_DATE            DATETIME, --拟稿年月日；个性字段；
  FORM_COMMON_ID         NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);




COMMENT ON TABLE WF_PROCESS_INSTANCE IS '流程实例表';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.ID IS '主键';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.CURRENT_NODE_ID IS '当前所处节点的ID';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.CREATOR_ID IS '创建流程的用户的ID';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.CREATOR_NAME IS '创建流程的用户名称';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.LAST_UPDATED_TIME IS '最新流转时间';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.PROCESS_VERSION_ID IS '有效流程定义版本ID';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.FORM_COMMON_ID IS '公用表单ID';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.FORM_DEF_ID IS '个性表单简称';
COMMENT ON COLUMN WF_PROCESS_INSTANCE.FORM_DETAIL_ID IS '个性表单ID';

COMMENT ON TABLE WF_CURRENT_TASK_INFO IS '代办任务表';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.ID IS '主键';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.PRO_INST_ID IS '当前任务所属流程实例的id';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.ASSIGNEE IS '接收者（人，角色）id';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.STATUS IS '任务的状态：未接收、已接收、已办结';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.CREATOR_ID IS '创建者（人）id';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.CREATOR_NAME IS '创建者（人）名字';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.LAST_UPDATED_TIME IS '最新操作(流转，修改)时间';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.TASK_TYPE IS '任务类型';
COMMENT ON COLUMN WF_CURRENT_TASK_INFO.ASSIGNEE_TYPE IS '接收者类型';

COMMENT ON TABLE WF_HISTORY_TASK_INFO IS '任务流转记录表';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.ID IS '主键';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.PRO_INST_ID IS '任务所属流程实例的id';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.FROM_NODE_ID IS '起始节点';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.TO_NODE_ID IS '目标节点';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.OPERATE_TIME IS '操作时间';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.OPERATOR_ID IS '流转操作人ID';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.OPERATOR_NAME IS '流转操作人姓名';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.OPERATOR_DEPART_ID IS '发起流转人所属部门ID';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.OPERATOR_DEPART_NAME IS '发起流转人所属部门名';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.OPINION IS '意见 暂未使用';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.FROM_NODE_NAME IS '出发节点名';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.TO_NODE_NAME IS '接收节点名';
COMMENT ON COLUMN WF_HISTORY_TASK_INFO.TASK_TYPE IS '任务类型';

COMMENT ON TABLE WF_PROCESS_DEF_MANAGE IS '流程类型表';
COMMENT ON COLUMN WF_PROCESS_DEF_MANAGE.ID IS '主键';
COMMENT ON COLUMN WF_PROCESS_DEF_MANAGE.NAME IS '名称';
COMMENT ON COLUMN WF_PROCESS_DEF_MANAGE.DESCRIPTION IS '描述';
COMMENT ON COLUMN WF_PROCESS_DEF_MANAGE.ORDER_NUM IS '排序字段';
COMMENT ON COLUMN WF_PROCESS_DEF_MANAGE.FORM_DEF_ID IS '个性表单简称';

COMMENT ON TABLE WF_PROCESS_DEF_VERSION IS '流程定义表';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.ID IS '主键';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.PROCESS_DEF_ID IS '流程类型id';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.VERSION IS '版本号';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.FILE_NAME IS 'xml文件名';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.FILE_PATH IS 'xml文件所在路径';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.IS_ACTIVE IS '是否启用';
COMMENT ON COLUMN WF_PROCESS_DEF_VERSION.DESCRIPTION IS '描述';

COMMENT ON TABLE WF_FORM_COMMON IS '公用表单表';
COMMENT ON COLUMN WF_FORM_COMMON.ID IS '主键';
COMMENT ON COLUMN WF_FORM_COMMON.EMERGENCE_LEVEL IS '紧急程度';
COMMENT ON COLUMN WF_FORM_COMMON.PUBLICITY_LEVEL IS '公开级别';
COMMENT ON COLUMN WF_FORM_COMMON.DOC_TYPE IS '文种';
COMMENT ON COLUMN WF_FORM_COMMON.SECRET_FORM_ID IS '定密单ID';
COMMENT ON COLUMN WF_FORM_COMMON.SECRET_LEVEL IS '定密单密级';
COMMENT ON COLUMN WF_FORM_COMMON.DEPT_ID IS '拟稿部门ID';
COMMENT ON COLUMN WF_FORM_COMMON.DOC_YEAR IS '年份';
COMMENT ON COLUMN WF_FORM_COMMON.DOC_NUMBER IS '号';
COMMENT ON COLUMN WF_FORM_COMMON.TITLE IS '标题';
COMMENT ON COLUMN WF_FORM_COMMON.NOT_OPEN_REASON IS '不予公开理由';
COMMENT ON COLUMN WF_FORM_COMMON.OTHER_REASON IS '不予公开的其他理由';
COMMENT ON COLUMN WF_FORM_COMMON.NUMBER_OF_COPY IS '打印份数';
COMMENT ON COLUMN WF_FORM_COMMON.FORM_DETAIL_ID IS '个性表单id';
COMMENT ON COLUMN WF_FORM_COMMON.FORM_DETAIL_TYPE IS '个性表单简称';
COMMENT ON COLUMN WF_FORM_COMMON.DEPART_NAME IS '拟稿部门简称';
COMMENT ON COLUMN WF_FORM_COMMON.DOC_PREFIX IS '文号前缀';
COMMENT ON COLUMN WF_FORM_COMMON.DOC_FULL_NAME IS '文号全称';

COMMENT ON TABLE WF_FORM_FAWEN IS '长城电子发文';
COMMENT ON COLUMN WF_FORM_FAWEN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_FAWEN.RELATED_RECEIVE_DOC_ID IS '关联收文号';
COMMENT ON COLUMN WF_FORM_FAWEN.SEND_TO_MAIN IS '主送';
COMMENT ON COLUMN WF_FORM_FAWEN.SEND_TO_CC IS '抄送';
COMMENT ON COLUMN WF_FORM_FAWEN.HE_GAO IS '核稿';
COMMENT ON COLUMN WF_FORM_FAWEN.HUI_GAO IS '会稿';
COMMENT ON COLUMN WF_FORM_FAWEN.HUI_QIAN IS '会签';
COMMENT ON COLUMN WF_FORM_FAWEN.SHEN_HE IS '审核';
COMMENT ON COLUMN WF_FORM_FAWEN.QIAN_FA IS '签发';
COMMENT ON COLUMN WF_FORM_FAWEN.NI_GAO_USERID IS '拟稿人id';
COMMENT ON COLUMN WF_FORM_FAWEN.NI_GAO_USERNAME IS '拟稿人姓名';
COMMENT ON COLUMN WF_FORM_FAWEN.NI_GAO_DATE IS '拟稿日期';
COMMENT ON COLUMN WF_FORM_FAWEN.FORM_COMMON_ID IS '公用表单ID';

COMMENT ON TABLE WF_FORM_JXWSHOUWEN IS '长城电子收文';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.INCOMING_DOC_DEPART IS '来文单位';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.INCOMING_DOC_NUM IS '来文文号';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.INCOMING_NUM IS '来文份数';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.RECEIVE_DATE IS '收文日期';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.RECEIVE_DOC_NUM IS '收文文号';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.LEADER_OPINION IS '领导批示';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.TODO_OPINION IS '拟办意见';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.NI_BAN IS '拟办';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.NI_GAO_DATA IS '拟稿日期';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.SHEN_HE IS '审核';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.SHEN_HE_DATE IS '审核日期';
COMMENT ON COLUMN WF_FORM_JXWSHOUWEN.FORM_COMMON_ID IS '通用表单的id';

COMMENT ON TABLE WF_FORM_JXWSJSHOUWEN IS '长城电子上级来文收文';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.RECEIVE_SERIAL_NUM IS '收文编号';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.RECEIVE_DATE IS '收文日期';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.INCOMING_NUM IS '收文分数';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.INCOMING_ZI_HAO IS '来文字号';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.INCOMING_DOC_DEPART IS '来文单位';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.ATTACH_DESC IS '附件说明';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.READ_OPINION IS '阅示意见';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.TODO_OPINION IS '办理意见';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.REGISTER_USER IS '登记人';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.REGISTER_DATE IS '登记时间';
COMMENT ON COLUMN WF_FORM_JXWSJSHOUWEN.FORM_COMMON_ID IS '通用表单的id';

COMMENT ON TABLE WF_FORM_JXWXINHAN IS '长城电子信函收文';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.INCOMING_DOC_DEPART IS '来文单位';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.INCOMING_DOC_NUM IS '来文文号';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.RECEIVE_DATE IS '收到日期';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.DOC_TYPE IS '类别';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.RECEIVE_DOC_NUM IS '收文文号';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.DOC_ABSTRACT IS '摘要';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.LIUZHUAN_OPINION IS '流转意见';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.RECEIVE_USER IS '收件人';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.SHOUJIAN_DATE IS '收件时间';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.AUDIT_USER IS '审核人';
COMMENT ON COLUMN WF_FORM_JXWXINHAN.FORM_COMMON_ID IS '通用表单的id';

COMMENT ON TABLE WF_FORM_JXWDWSHOUWEN IS '长城电子党委收文';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.INCOMING_DOC_DEPART IS '来文单位';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.INCOMING_DOC_NUM IS '来文文号';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.INCOMING_NUM IS '来文份数';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.RECEIVE_DATE IS '收文日期';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.RECEIVE_DOC_NUM IS '收文文号';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.LEADER_OPINION IS '领导批示';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.TODO_OPINION IS '拟办意见';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.NI_BAN IS '拟办';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.NI_GAO_DATA IS '拟稿日期';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.SHEN_HE IS '审核';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.SHEN_HE_DATE IS '审核日期';
COMMENT ON COLUMN WF_FORM_JXWDWSHOUWEN.FORM_COMMON_ID IS '通用表单的id';

COMMENT ON TABLE WF_FORM_JXWDWFAWEN IS '长城电子党委发文';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.RELATED_RECEIVE_DOC_ID IS '关联收文号';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.SEND_TO_MAIN IS '主送';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.SEND_TO_CC IS '抄送';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.HE_GAO IS '核稿';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.HUI_GAO IS '会稿';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.HUI_QIAN IS '会签';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.SHEN_HE IS '审核';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.QIAN_FA IS '签发';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.THEME IS '主题词';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.NI_GAO_USERNAME IS '拟稿人';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.NI_GAO_DATE IS '拟稿年月日';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.FORM_COMMON_ID IS '通用表单的id';

COMMENT ON TABLE WF_FORM_GFKGBFAWEN IS '国防科工办发文';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.ID IS '主键';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.RELATED_RECEIVE_DOC_ID IS '关联收文号';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.SEND_TO_MAIN IS '主送';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.SEND_TO_CC IS '抄送';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.HE_GAO IS '核稿';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.HUI_GAO IS '会稿';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.HUI_QIAN IS '会签';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.SHEN_HE IS '审核';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.QIAN_FA IS '签发';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.NI_GAO_USERID IS '拟稿人id';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.NI_GAO_USERNAME IS '拟稿人姓名';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.NI_GAO_DATE IS '拟稿年月日';
COMMENT ON COLUMN WF_FORM_GFKGBFAWEN.FORM_COMMON_ID IS '通用表单的id';
COMMIT;


