DROP TABLE WF_FORM_JXWDWFAWEN;
COMMIT;
--1.长城电子党委发文
CREATE TABLE WF_FORM_JXWDWFAWEN (
  ID                     NUMBER, --	主键
  RELATED_RECEIVE_DOC_ID NUMBER, --关联收文号；个性字段；
  SEND_TO_MAIN           VARCHAR2(512), --主送；个性字段；
  SEND_TO_CC             VARCHAR2(512), --抄送；个性字段；
  HE_GAO                 VARCHAR2(512), --核稿；个性字段；
  HUI_GAO                VARCHAR2(512), --会稿；个性字段；
  HUI_QIAN               VARCHAR2(512), --会签；个性字段；
  SHEN_HE                VARCHAR2(512), --审核；个性字段；
  QIAN_FA                VARCHAR2(512), --签发；个性字段；
  NI_GAO_USERID          NUMBER, --拟稿人id；个性字段；
  NI_GAO_USERNAME        VARCHAR2(64), --拟稿人姓名，冗余字段；个性字段；
  JIAO_DUI_USERID        NUMBER, --校对人id；个性字段；
  JIAO_DUI_USERNAME      VARCHAR2(64), --校对人姓名，冗余字段；个性字段；
  NI_GAO_DATE            DATETIME, --拟稿年月日；个性字段；
  ZHU_SONG_NUM           NUMBER, -- 主送份数
  CHAO_SONG_NUM          NUMBER, -- 抄送份数
  ZHI_NENG_CHU_SHI_NUM   NUMBER, -- 职能处室份数
  GUI_DANG_NUM           NUMBER, -- 归档份数
  OTHER_NUM              NUMBER, -- 其他份数
  FORM_COMMON_ID         NUMBER, --通用表单的id,
  PRIMARY KEY (ID)
);
COMMIT;

COMMENT ON TABLE WF_FORM_JXWDWFAWEN IS '长城电子党委发文文个性表单';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.ID IS '主键';

COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.RELATED_RECEIVE_DOC_ID IS '关联收文号';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.SEND_TO_MAIN IS '主送';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.SEND_TO_CC IS '抄送';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.HE_GAO IS '核稿';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.HUI_GAO IS '会稿';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.HUI_QIAN IS '会签';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.SHEN_HE IS '审核';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.QIAN_FA IS '签发';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.NI_GAO_USERID IS '拟稿人id';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.NI_GAO_USERNAME IS '拟稿人姓名';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.JIAO_DUI_USERID IS '校对人id';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.JIAO_DUI_USERNAME IS '校对人姓名';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.NI_GAO_DATE IS '拟稿日期';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.ZHU_SONG_NUM IS '主送份数';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.CHAO_SONG_NUM IS '抄送份数';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.ZHI_NENG_CHU_SHI_NUM IS '职能处室份数';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.GUI_DANG_NUM IS '归档份数';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.OTHER_NUM IS '其他份数';
COMMENT ON COLUMN WF_FORM_JXWDWFAWEN.FORM_COMMON_ID IS '公用表单ID';
COMMIT;

