-- update  ORGUSER   set  GENDER ='0' where GENDER='女';
-- update  ORGUSER   set  GENDER ='1' where GENDER='男';
--统一数据展示

update  ORGUSER   set  FLAG =(select JXWOAUniversalSeq.nextval from dual) where FLAG !=1 AND FLAG !=9 or FLAG is NULL ;

CREATE UNIQUE INDEX UIDX_ORGUSER_USERNAMEANDFLAG ON ORGUSER (USERNAME, FLAG);

/*唯一性索引*/
-- CREATE TABLE TEST ( "C1" INT, "C2" INT);
-- CREATE UNIQUE INDEX U_INDEX ON TEST(C2);
-- INSERT INTO TEST VALUES(1,1);
-- ALTER INDEX U_INDEX UNUSABLE;
-- INSERT INTO TEST VALUES(1,2);
-- DROP INDEX    UIDX_ORGDU_USERID_DEPTID;
-- ALTER INDEX U_INDEX REBUILD;
-- INSERT INTO TEST VALUES(1,3);
-- INSERT INTO TEST VALUES(1,1);
