alter table WF_FORM_COMMON add (JIN_BAN_DATE datetime(6));
COMMENT ON COLUMN WF_FORM_COMMON.JIN_BAN_DATE IS '人大政协报批单经办日期';

alter table WF_FORM_COMMON add (NI_GAO_DATE datetime(6));
COMMENT ON COLUMN WF_FORM_COMMON.NI_GAO_DATE IS '人大政协报批单拟稿日期';

alter table WF_FORM_COMMON add (JIN_BAN_ID NUMBER);
COMMENT ON COLUMN WF_FORM_COMMON.JIN_BAN_ID IS '经办人id';

alter table WF_FORM_COMMON add (JIN_BAN_NAME VARCHAR2(64));
COMMENT ON COLUMN WF_FORM_COMMON.JIN_BAN_NAME IS '经办人姓名';

INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF, DOC_PREFIX) VALUES (600000, '政协报批', '办理意见报批', null, 'blyjbpzx', 'handlingwork', '1', null, null, null, null, null, null, null, null, null, '{ "chushi": [ "1", "2" ], "bangongshi": [ "3","4" ], "weilingdao": [ "5" ] }', '政协报批');
INSERT INTO WF_PROCESS_DEF_MANAGE (ID, NAME, DESCRIPTION, ORDER_NUM, FORM_DEF_ID, PRO_DEF_GROUP_ID, FLAG, PUBLISH_OFFICE, PUBLISH_SYMBOL, UNIFIED_SOCIAL_CREDIT_CODE, DOC_OID, SEND_DEPART_CODE, SERIAL_NUMBER, PUBLISH_OFFICE_BRIF, ISSUE_PERSON, ISSUE_PERSON_POST, OPTION_SHOW_CONF, DOC_PREFIX) VALUES (875133, '人大报批', '办理意见报批', null, 'blyjbprd', 'handlingwork', '1', null, null, null, null, null, null, null, null, null, '{ "chushi": [ "1", "2" ], "bangongshi": [ "3","4" ], "weilingdao": [ "5" ] }', '人大报批');
INSERT INTO WF_PROCESS_DEF_VERSION (ID, PROCESS_DEF_ID, VERSION, FILE_NAME, FILE_PATH, IS_ACTIVE, DESCRIPTION) VALUES (875134, 875133, 1, 'a0cb27f0-67a2-4dd4-9bf3-94aeb9302471', 'a0cb27f0-67a2-4dd4-9bf3-94aeb9302471.xml', '1', '人大报批');
INSERT INTO WF_PROCESS_DEF_VERSION (ID, PROCESS_DEF_ID, VERSION, FILE_NAME, FILE_PATH, IS_ACTIVE, DESCRIPTION) VALUES (875441, 600000, 1, 'a0cb27f0-67a2-4dd4-9bf3-94aeb930247', 'a0cb27f0-67a2-4dd4-9bf3-94aeb9302471.xml', '1', '政协报批');
commit;